### ISSUE TITLE
Lua warning from factorio-side lua mod script

### ISSUE THREAD

**Issue by OvermindDL1** [L0laapk3/FactorioMaps#15]
```lua
[GAME]  159.678 Warning LuaGameScript.cpp:1545: luaremove_path error: Scripts can only use file space inside of script-output
```

**Comment by L0laapk3** [comment]
I've investigated this warning before, and that error is actually quite
misleading, its actually caused by deleting folders that are inside folders
that don't exist. But because of determinism in the lua api I can't
actually check if the folder exists or not. I've already reported it but
I've decided creating a bunch of folders just to delete them and be able to
hide a misleading warning was just not worth it.

>

**Comment by L0laapk3** [comment]
https://forums.factorio.com/viewtopic.php?f=7&t=64873

**Comment by OvermindDL1** [comment]
Awesome!  Thanks for the followup!  :-)
