### ISSUE TITLE
How to use with old factorio maps?

### ISSUE THREAD

**Issue by fireduck64** [L0laapk3/FactorioMaps#30]
I have a bunch of old maps that I saved with earlier versions of FactorioMaps.  They used the Google Maps API and now don't work (even if I put in a valid API key).

It appears that the new version doesn't use Google Maps but I'm guessing still uses the same image format and layout.  Is there a way to generate a new index and library files and mapInfo.js for an old map?

Note: many of these maps were from factorio versions and mod packages that would be hard to reproduce so I can't use the new process and go from save to map.

**Comment by fireduck64** [comment]
Anyone else facing my problems:
1) Add an API key.
2) Change code to not do a url change on every recenter.  See:
https://storage.googleapis.com/factorio-1209k-maps/Vista/index.html

Notice that I changed:
map.addListener('center_changed', checkBounds);
to
map.addListener('center_changed', update_map);

**Comment by fireduck64** [comment]
There was a related issue: https://github.com/xkjyeah/vue-google-maps/issues/330

**Comment by L0laapk3** [comment]
The reason I started working on my own version of factoriomaps is because the old version had a whole list of annoyances. Converting the old maps isn't supported by me, however however if you're not afraid to tinker a bit with python, I can give you a list of what needs to happen to make it work:
- You need to move the images to a folder structure  containing the timestamp, surface, daytime. Best to make an example and manually create the same structure. You'll also have to create your own mapInfo.json.
- the images have one folder for each zoom level. I recommend deleting all zoom levels but the one with the highest detail, rename that folder to (zoom level)`20`, and call `python zoom.py` with the appropriate arguments. This will give you far improved quality when zoomed out.
- You will have to run `python ref.py` with the same arguments as zoom, this will generate an index of all the images which will be used in the webpage
- Finally to make the webpage work, you will have to basically run all the lines starting from https://github.com/L0laapk3/FactorioMaps/blob/v3.2.1/auto.py#L482 , I recommend you create a new python script, as you will have to also copy the variables created earlier and used in those lines of the script.

If I'm not mistaking, those steps should allow you to 'convert' your old maps. Good luck! :P

**Comment by L0laapk3** [comment]
Feel free to reopen if you have anymore questions.
