### ISSUE TITLE
scenario incompability: FactorioScenarioMultiplayerSpawn

### ISSUE THREAD

**Issue by mmuziek** [L0laapk3/FactorioMaps#53]
Well to be short the mod/script fails me.
i have no clue whats wrong its a saved map on my machine.
when i trigger the generation it trows a error however does generate the map but the map is blank with a black dot.
it also shows that its missing files.
https://imgur.com/c1DXpOj
https://imgur.com/O5q4RZ5
https://imgur.com/a9oawuo

**Comment by L0laapk3** [comment]
Can you include your savefile?

**Comment by mmuziek** [comment]
here you go hosted on own webserver due to size:
https://api.bitcubes.eu/Factorio.zip

**Comment by L0laapk3** [comment]
The error had nothing to do with it and I've already addressed that error.

How did you explore the area? The normal workflow for quite some time already has been to iterate over all the chunks, check which ones have been charted by any force, and render those. I'm really puzzled by how there are a total of zero chunks charted on the entire may by any force since I'd expect them to get charted the second you walk near them.

Do you have any more information about this? Is this some custom scenario shenanigans or a mod doing this? Its quite puzzling to me.

**Comment by mmuziek** [comment]
the chunck are mostly black however the path and such we made is visible now thanks

**Comment by mmuziek** [comment]
well i tried regenerating another snapshot as my map now is and it stays on cropping night
https://prnt.sc/qdb5d0
and doesnt go further (i have added the argument like u said)

**Comment by L0laapk3** [comment]
You have text selected, selecting text freezes commandline.

**Comment by mmuziek** [comment]
well i tried it again without touching my mouse
https://prnt.sc/qdj2za
is the result it keeps doing that.
when i finally had 1 good go i thought it shows a error about LINK in auto.py

**Comment by L0laapk3** [comment]
scenario incompability fix is now released, if you're having random errors still that are not related to this, feel free to open a new issue :)
