### ISSUE TITLE
Give warning popup to disable the mod

### ISSUE THREAD

**Issue by Brandjuh** [L0laapk3/FactorioMaps#9]
Hello,

I cannot walk anymore with the current save game since I tried out this mod, Crafting and walking are not working. How can I solve this?

Already tried to remove the mod from the mod folder and disabled it in the game as well from the save game but the problems stays. ATM I am 21 IRL days in the save so I do not want lose this save game.

**Comment by L0laapk3** [comment]
The mod performs some destructive behaviour in order to improve the maps.
While auto.py runs, you are NOT supposed to take control and quickly
overwrite your save before auto.py kills factorio again.

You can try running this command, it should mostly repair your world. But
please do not play with it while the python script is running, and
especially dont save as the script makes no effort to keep track of some
entity states or restore them when it overwrites them, and also your game
could get killed while you save which could corrupt your saves.

    /c for key, entity in pairs(game.players[event.player_index].surface.
find_entities_filtered({invert=true, name="hidden-electric-energy-interface"
})) do entity.active = true end

**Comment by Brandjuh** [comment]
I tried to run the mod (before the corruption) but it did not run. 
Seems like it did run something because I cannot walk/craft anymore, just tried the command but it did not work. I think I need to start a new save. 

Anyway, thanks for the quick answer.

**Comment by L0laapk3** [comment]
The mod is completely passive on its own. Only when you run the auto.py
scripts, it will get invoked.

Send me over your savefile and I will try to fix it.

Op do 27 dec. 2018 11:30 schreef Brandjuh <notifications@github.com>:

**Comment by Brandjuh** [comment]
Thanks in advance, I have uploaded it to my dropbox.
https://www.dropbox.com/sh/48ung1g442266lb/AABk2s8WEgBnZFttqiqCDzyCa?dl=0

**Comment by L0laapk3** [comment]
You can run the following command:

`/c for _,e in pairs(game.player.surface.find_entities()) do e.active = true end`

That fixed everything for me, let me know if theres any further problems with your save.
